In [66]:
import pandas as pd
import requests

In [67]:
# https://simplemaps.com/data/nl-cities
# https://en.wikipedia.org/wiki/List_of_cities_in_the_Netherlands_by_province
# https://en.wikipedia.org/wiki/Municipalities_of_the_Netherlands#cite_note-CBS_code-1
pop1 = pd.read_csv("data/processed/nl.csv")
pop2 = pd.read_csv("data/processed/nl2.csv")

In [68]:
pop4 = pd.concat([pop1,pop2],0).reset_index(drop=True)

<ipython-input-68-4b232ed9483d>:1: FutureWarning: In a future version of pandas all arguments of concat except for the argument 'objs' will be keyword-only
  pop4 = pd.concat([pop1,pop2],0).reset_index(drop=True)

In [69]:
pop4#[pop4['lat'].isna()]

,city,lat,lng,country,iso2,admin_name,capital,population,population_proper,Gemeentecode,GemeentecodeGM,Gemeentenaam,Provinciecode,ProvinciecodePV,Provincienaam
0,The Hague,52.0767,4.2986,Netherlands,NL,Zuid-Holland,primary,1406000.0,501725.0,NaN,NaN,NaN,NaN,NaN,NaN
1,Amsterdam,52.3667,4.8833,Netherlands,NL,Noord-Holland,primary,862965.0,862965.0,NaN,NaN,NaN,NaN,NaN,NaN
2,Utrecht,52.0908,5.1222,Netherlands,NL,Utrecht,admin,640000.0,316448.0,NaN,NaN,NaN,NaN,NaN,NaN
3,Rotterdam,51.9225,4.4792,Netherlands,NL,Zuid-Holland,minor,631155.0,631155.0,NaN,NaN,NaN,NaN,NaN,NaN
4,Eindhoven,51.4408,5.4778,Netherlands,NL,Noord-Brabant,minor,398053.0,209620.0,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1291,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,879.0,GM0879,Zundert,30.0,PV30,Noord-Brabant
1292,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,301.0,GM0301,Zutphen,25.0,PV25,Gelderland
1293,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1896.0,GM1896,Zwartewaterland,23.0,PV23,Overijssel
1294,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,642.0,GM0642,Zwijndrecht,28.0,PV28,Zuid-Holland
1295,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,193.0,GM0193,Zwolle,23.0,PV23,Overijssel

In [ ]:
# pop4['concat'] = pop4['city'] + " " + pop4['admin_name']

In [6]:
# pop4 = pop4[pop4['lat'].isna()]

In [56]:
pop4 = pd.read_csv("data/processed/nl2.csv")
pop4[(pop4['city']=='Sluis') & (pop4['lat']=='Zeeland')]

Empty DataFrame
Columns: [Unnamed: 0, city, lat, lng, country, iso2, admin_name, capital, population, population_proper]
Index: []

In [7]:
lat=[]
lon=[]
city_ = []
province_ =[]
error=[]

for city, province in zip(pop4['city'],pop4['admin_name']):
    try:
        url = "https://nominatim.openstreetmap.org/search?q="+city+" "+province+"&format=geojson"
        r = requests.get(url)
        lat.append(r.json()['features'][0]['geometry']['coordinates'][0])
        lon.append(r.json()['features'][0]['geometry']['coordinates'][1])
        province_.append(province)
        city_.append(city)
        print(city, province)
    except:
        print('##########', city, province)
        error.append(city+" "+province)
        pass

Aa en Hunze Drenthe
Achtkarspelen FryslÃ¢n
Albrandswaard Zuid-Holland
Alphen-Chaam Noord-Brabant
Altena Noord-Brabant
Ameland FryslÃ¢n
Beekdaelen Limburg
Beemster Noord-Holland
Berg en Dal Gelderland
Bergen (L.) Limburg
Bergen (NH.) Noord-Holland
########## Berkelland Gelderland
Bernheze Noord-Brabant
De Bilt Utrecht
Bloemendaal Noord-Holland
########## Bodegraven-Reeuwijk Zuid-Holland
########## Borger-Odoorn Drenthe
########## Borsele Zeeland
Bronckhorst Gelderland
########## Bunschoten Utrecht
Dantumadiel FryslÃ¢n
Dinkelland Overijssel
########## Drechterland Noord-Holland
########## Echt-Susteren Limburg
Edam-Volendam Noord-Holland
Eemsdelta Groningen
Eijsden-Margraten Limburg
De Fryske Marren FryslÃ¢n
Geldrop-Mierlo Noord-Brabant
Gemert-Bakel Noord-Brabant
Gilze en Rijen Noord-Brabant
Goeree-Overflakkee Zuid-Holland
Gooise Meren Noord-Holland
's-Gravenhage Zuid-Holland
Gulpen-Wittem Limburg
Haarlemmermeer Noord-Holland
Halderberge Noord-Brabant
Heeze-Leende Noord-Brabant
's-Hertogenbosch Noord-Brabant
Heusden Noord-Brabant
Hoeksche Waard Zuid-Holland
Hof van Twente Overijssel
Het Hogeland Groningen
########## Hollands Kroon Noord-Holland
Horst aan de Maas Limburg
Kaag en Braassem Zuid-Holland
Koggenland Noord-Holland
Krimpenerwaard Zuid-Holland
Laarbeek Noord-Brabant
Landerd Noord-Brabant
########## Lansingerland Zuid-Holland
Leidschendam-Voorburg Zuid-Holland
Leudal Limburg
Lingewaard Gelderland
Maasdriel Gelderland
########## Maasgouw Limburg
Meierijstad Noord-Brabant
Midden-Delfland Zuid-Holland
Midden-Drenthe Drenthe
Midden-Groningen Groningen
Mill en Sint Hubert Noord-Brabant
Moerdijk Noord-Brabant
Molenlanden Zuid-Holland
Montferland Gelderland
Mook en Middelaar Limburg
Neder-Betuwe Gelderland
Nieuwkoop Zuid-Holland
Nissewaard Zuid-Holland
Noardeast-FryslÃ¢n FryslÃ¢n
Noord-Beveland Zeeland
Noordenveld Drenthe
Noordoostpolder Flevoland
Nuenen, Gerwen en Nederwetten Noord-Brabant
Oldambt Groningen
Olst-Wijhe Overijssel
Oost Gelre Gelderland
Ooststellingwerf FryslÃ¢n
Opsterland FryslÃ¢n
Oude IJsselstreek Gelderland
Ouder-Amstel Noord-Holland
Overbetuwe Gelderland
Peel en Maas Limburg
Pekela Groningen
Pijnacker-Nootdorp Zuid-Holland
Reimerswaal Zeeland
Renkum Gelderland
Reusel-De Mierden Noord-Brabant
Rijssen-Holten Overijssel
Roerdalen Limburg
De Ronde Venen Utrecht
Schouwen-Duiveland Zeeland
Sittard-Geleen Limburg
########## Sluis Zeeland
Smallingerland FryslÃ¢n
Stede Broec Noord-Holland
Steenwijkerland Overijssel
Stichtse Vecht Utrecht
SÃºdwest-FryslÃ¢n FryslÃ¢n
Terschelling FryslÃ¢n
Texel Noord-Holland
Teylingen Zuid-Holland
Twenterand Overijssel
Tytsjerksteradiel FryslÃ¢n
########## Utrechtse Heuvelrug Utrecht
Valkenburg aan de Geul Limburg
Velsen Noord-Holland
########## Vijfheerenlanden Utrecht
########## Vlieland FryslÃ¢n
Voorst Gelderland
Waadhoeke FryslÃ¢n
Waterland Noord-Holland
########## West Betuwe Gelderland
########## West Maas en Waal Gelderland
########## Westerkwartier Groningen
Westerveld Drenthe
########## Westerwolde Groningen
########## Westland Zuid-Holland
########## Weststellingwerf FryslÃ¢n
########## Westvoorne Zuid-Holland
########## Wijdemeren Noord-Holland
De Wolden Drenthe
########## Wormerland Noord-Holland
Zuidplas Zuid-Holland
########## Zwartewaterland Overijssel

In [46]:
final = pd.DataFrame({'lat_':lat,'lng_':lon,'admin_name':province_,'city':city_})
final

        lat_       lng_     admin_name           city
0   6.729452  52.981439        Drenthe    Aa en Hunze
1   6.150764  53.207517        FryslÃ¢n  Achtkarspelen
2   4.435285  51.852427   Zuid-Holland  Albrandswaard
3   4.871360  51.506896  Noord-Brabant   Alphen-Chaam
4   4.943673  51.769744  Noord-Brabant         Altena
..       ...        ...            ...            ...
95  5.610798  53.246005        FryslÃ¢n      Waadhoeke
96  5.058110  52.443507  Noord-Holland      Waterland
97  6.311162  52.828453        Drenthe     Westerveld
98  6.338952  52.705585        Drenthe      De Wolden
99  4.613451  51.999579   Zuid-Holland       Zuidplas

[100 rows x 4 columns]

In [47]:
# pop3 = pop3.drop(columns=["admin_name_y"]).rename(columns={"admin_name_x":"admin_name"})
pop3

,city,lat,lng,country,iso2,admin_name,capital,population,population_proper
0,The Hague,52.0767,4.2986,Netherlands,NL,Zuid-Holland,primary,1406000.0,501725.0
1,Amsterdam,52.3667,4.8833,Netherlands,NL,Noord-Holland,primary,862965.0,862965.0
2,Utrecht,52.0908,5.1222,Netherlands,NL,Utrecht,admin,640000.0,316448.0
3,Rotterdam,51.9225,4.4792,Netherlands,NL,Zuid-Holland,minor,631155.0,631155.0
4,Eindhoven,51.4408,5.4778,Netherlands,NL,Noord-Brabant,minor,398053.0,209620.0
...,...,...,...,...,...,...,...,...,...
939,Wommels,53.1088,5.5875,Netherlands,NL,FryslÃ¢n,minor,NaN,NaN
940,Sellingen,52.9464,7.1514,Netherlands,NL,Groningen,minor,NaN,NaN
941,Ballum,53.4441,5.6876,Netherlands,NL,FryslÃ¢n,minor,NaN,NaN
942,West-Terschelling,53.3608,5.2156,Netherlands,NL,FryslÃ¢n,minor,NaN,NaN
943,Oost-Vlieland,53.2959,5.0665,Netherlands,NL,FryslÃ¢n,minor,NaN,NaN

In [48]:
final_2 = pd.merge(pop3,final, on=['admin_name','city'], how='left')
final_2

,city,lat,lng,country,iso2,admin_name,capital,population,population_proper,lat_,lng_
0,The Hague,52.0767,4.2986,Netherlands,NL,Zuid-Holland,primary,1406000.0,501725.0,NaN,NaN
1,Amsterdam,52.3667,4.8833,Netherlands,NL,Noord-Holland,primary,862965.0,862965.0,NaN,NaN
2,Utrecht,52.0908,5.1222,Netherlands,NL,Utrecht,admin,640000.0,316448.0,NaN,NaN
3,Rotterdam,51.9225,4.4792,Netherlands,NL,Zuid-Holland,minor,631155.0,631155.0,NaN,NaN
4,Eindhoven,51.4408,5.4778,Netherlands,NL,Noord-Brabant,minor,398053.0,209620.0,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...
939,Wommels,53.1088,5.5875,Netherlands,NL,FryslÃ¢n,minor,NaN,NaN,NaN,NaN
940,Sellingen,52.9464,7.1514,Netherlands,NL,Groningen,minor,NaN,NaN,NaN,NaN
941,Ballum,53.4441,5.6876,Netherlands,NL,FryslÃ¢n,minor,NaN,NaN,NaN,NaN
942,West-Terschelling,53.3608,5.2156,Netherlands,NL,FryslÃ¢n,minor,NaN,NaN,NaN,NaN
943,Oost-Vlieland,53.2959,5.0665,Netherlands,NL,FryslÃ¢n,minor,NaN,NaN,NaN,NaN

In [49]:
final_2.loc[final_2['lat'].isna(),'lat'] = final_2['lat_']
final_2.loc[final_2['lng'].isna(),'lng'] = final_2['lng_']

In [50]:
final_2.drop(columns=['lat_','lng_']).to_csv("data/processed/nl2.csv")

In [ ]:
sdasdasdasdasdas

In [ ]:
pop4 = final_2.loc[final_2['lat'].isna()]


import requests
lat=[]
lon=[]
city_ = []
province_ =[]
error=[]
places = list(pop4['city'] + " " + pop4['Provincienaam'])

for city, province in zip(pop4['city'],pop4['Provincienaam']):
    try:
        url = "https://nominatim.openstreetmap.org/search?q="+city+" "+province+"&format=geojson"
        r = requests.get(url)
        lat.append(r.json()['features'][0]['geometry']['coordinates'][0])
        lon.append(r.json()['features'][0]['geometry']['coordinates'][1])
        province_.append(province)
        city_.append(city)
        print(city, province)
    except:
        print('##########', city, province)
        error.append(city+" "+province)
        pass

In [ ]:
final = pd.DataFrame({'lat_':lat,'lng_':lon,'Provincienaam':province_,'city':city_})
final_2 = pd.merge(final_2,final, on=['Provincienaam','city'], how='left')
# final_2.loc[final_2['lat'].isna(),'lat'] = final_2['lat_']
# final_2.loc[final_2['lng'].isna(),'lng'] = final_2['lng_']
# final_2.loc[final_2['lat'].isna()]

final_2

In [ ]:
dasdasda

In [ ]:
from geopy.geocoders import Nominatim
geolocator = Nominatim(user_agent="ericson")
df_list = 
address=[]
latitude=[]
longitude=[]
for i in range(len(df_list)):
    print(i)
    print(df_list[i])
    location = geolocator.geocode(df_list[i])
    address.append(location.address)
    latitude.append(location.latitude)
    longitude.append(location.longitude)

In [ ]:
r.json()['features'][-1]

In [ ]:
pop3['city'] + " " + pop3['Provincienaam']

In [ ]:
asdasdasda

In [ ]:
* #

In [ ]:
a_s[a_s['city'].str.contains('.*Stein.*')]

In [ ]:
URL = 'https://www.numbeo.com/cost-of-living/country_result.jsp?country=Netherlands'
response = get(URL)
soup = BeautifulSoup(response.text, 'html.parser')
city_form = soup.find('form', {'class': 'standard_margin'})
city_form = [values['value'] for values in city_form('option')]
meu_01=[]

In [ ]:
for city in city_form[:]:
    URL = 'https://www.numbeo.com/cost-of-living/city-estimator/in/'
    IRL = '?Recalculated=Submit+to+Recalculate&displayCurrency=EUR&members=1&restaurants_percentage=10.0&inexpensive_restaurants_percentage=50.0&drinking_coffee_outside=100.0&going_out_monthly=4.2&smoking_packs_per_day=0.0&alcoholic_drinks=25.0&type_of_food=0&driving_car=0.0&taxi_consumption=0.0&paying_for_public_transport=Monthly%2C+All+Members&sport_memberships=100.0&vacation=0.0&clothing_and_shoes=50.0&rent=none&kindergarten_count=0&private_schools_count=0'
    benefit=[]
    price=[]
    city = city.replace(' ','-')
    city = city.replace('(','')
    city = city.replace(')','')
    try:
        link = URL+city+IRL
        response = get(URL+city+IRL)
        soup = BeautifulSoup(response.text, 'html.parser')
        if len(soup.find_all('nav',{'class':'breadcrumb'}))==0:
            link=URL+city+'-Netherlands'+IRL
            response = get(link)
            soup = BeautifulSoup(response.text, 'html.parser')
        else:
            pass
        benefit = (soup.find_all('th',{'class':'tr_highlighted_menu'})[-1].get_text())
        price = (soup.find_all('th',{'class':'th_no_highlight_a_right'})[-1].get_text())
        meu_01.append({'benefit':benefit,'price':price,'city':city,'url':link})
    except:
        pass

In [ ]:
df = pd.DataFrame(meu_01)
df = df[df['price']!=' ?'].reset_index(drop=True)
df['price'] = df['price'].str.replace('?','0',regex=True)
df['price'] = df['price'].str.replace('\D','',regex=True)
df['price'] = (df['price'].astype(float))/100

In [ ]:
df.loc[df['city']=='The-Hague-Den-Haag','city'] = 'The Hague'
df.loc[df['city']=='Halle','city'] = 'Hall'
df.loc[df['city'].str.contains('Hertogenbosch'),'city'] = "â€™s-Hertogenbosch"

In [ ]:
fdf = pd.merge(df,a_s[['city','lng']],on='city',how='left')
fdf[fdf['lng'].isna()]

In [ ]:
a_s[a_s['city'].str.contains('Voorburg')]

In [ ]:
a_s[(a_s['lat']<=52.07)&(a_s['lat']>=52.06)]

In [ ]:
geolocator.geocode("'s-Hertogenbosch Nederland")

In [ ]:
from geopy.geocoders import Nominatim
geolocator = Nominatim(user_agent="ericson")
df_list = df['city'].unique() + " Nederland"
address=[]
latitude=[]
longitude=[]
for i in range(len(df_list)):
    print(i)
    print(df_list[i])
    location = geolocator.geocode(df_list[i])
    address.append(location.address)
    latitude.append(location.latitude)
    longitude.append(location.longitude)

In [ ]:
df['address'] = address
df['latitude'] = latitude
df['longitude'] = longitude

df['latitude'] = round(df['latitude'],7)
df['longitude'] = round(df['longitude'],7)

In [ ]:
df['benefit'] = 'costs'
df['link'] = "<a target='_blank' href=" + (df['url']).astype(str) + ">" + 'Source' + "</a>"
df = df.drop_duplicates().sort_values('price', ascending=False).reset_index(drop=True)

In [ ]:
import numpy as np
def haversine(lat1, lon1, lat2, lon2):
    earth_radius=6371
    lat1, lon1, lat2, lon2 = np.radians([lat1, lon1, lat2, lon2])
    a = np.sin((lat2-lat1)/2.0)**2 + np.cos(lat1) * np.cos(lat2) * np.sin((lon2-lon1)/2.0)**2
    return earth_radius * 2 * np.arcsin(np.sqrt(a))

df['latitude1'] = 51.907183
df['longitude1'] = 4.472815
df['distance'] = haversine(df['latitude'], df['longitude'], df['latitude1'],df['longitude1'])
df['distance'] = round(df['distance'],2)

In [ ]:
df

In [ ]:
ksjdhakjsdhkjashdkjashdkjahskdjhaskjdhaskjds
ksjdhakjsdhkjashdkjashdkjahskdjhaskjdhaskjds
ksjdhakjsdhkjashdkjashdkjahskdjhaskjdhaskjds

In [ ]:
df.reset_index(drop=True).to_csv('../../app/costs.csv')

In [ ]:
from bs4 import BeautifulSoup
from requests import get
import pandas as pd

In [ ]:
def  minha(URL,city):
    response = get(URL)
    soup = BeautifulSoup(response.text, 'html.parser')
    split1 = soup.find_all('tr',{'class':'tr_standard'})
    benefit = []
    col_factor = []
    price = []
    city_form=[]
    for i in range(len(split1)):
        try:
            benefit_ = split1[i].find('td').find(text=True)
        except:
            benefit_ = None
        try:
            col_factor_ = split1[i].find('span',{'class':'estimator_multiplier'}).find(text=True)
        except:
            col_factor_ = None
        try:
            price_ = split1[i].find('span',{'class':'price_in_units_for_analysis'}).find(text=True)
        except:
            price_ = None

        benefit.append(benefit_)
        col_factor.append(col_factor_)
        price.append(price_)
        city_form.append(city)
        
    return [benefit,col_factor,city_form,price]

In [ ]:
URL = 'https://www.numbeo.com/cost-of-living/country_result.jsp?country=Netherlands'
response = get(URL)
soup = BeautifulSoup(response.text, 'html.parser')
city_form = soup.find('form', {'class': 'standard_margin'})
city_form = [values['value'] for values in city_form('option')]
meu_01=[]

In [ ]:
for city in city_form[:]:
    URL = 'https://www.numbeo.com/cost-of-living/city-estimator/in/'+city
    my_dict_ = minha(URL,city)
    meu_01.append({'benefit':my_dict_[0],'col_factor':my_dict_[1],'city':my_dict_[2],'price':my_dict_[3]})

In [ ]:
df = pd.DataFrame({})
for i in range(len(meu_01)):
    df = pd.concat([df, pd.DataFrame(meu_01[i])],0)

In [ ]:
df['price'] = df['price'].str.replace('?','0',regex=True)
df['price']= df['price'].str.replace('\D','',regex=True)
df['price'] = (df['price'].astype(float))/100

In [ ]:
df['col_factor']= df['col_factor'].str.replace('x','',regex=True)
df['col_factor'] = (df['col_factor'].astype(float))/2

---

In [ ]:
# Import Libs
from folium.plugins import FastMarkerCluster
import io
import base64
import folium
import pandas as pd
import streamlit as st
from st_aggrid import AgGrid
import matplotlib.cm as cm
import numpy as np
import matplotlib.pyplot as plt
from matplotlib import cm
from matplotlib.colors import ListedColormap, LinearSegmentedColormap
import folium.plugins
import branca
import branca.colormap as cm
import folium.plugins
import branca
import branca.colormap as cm

In [ ]:
final = pd.read_csv('../../app/costs.csv', index_col=[0])
final_ = final[['price', 'city', 'url']].to_html(escape=False)
lats = final['latitude'].tolist()
lons = final['longitude'].tolist()
city = final['city'].tolist()
price = final['price'].tolist()
map = folium.Map(location=[52.2129919, 5.2793703],zoom_start=7, tiles="cartodbdark_matter")
feature_group = folium.FeatureGroup("Locations")
for lats, lons, price, city in zip(lats, lons, price, city):
    feature_group.add_child(
        folium.CircleMarker(
            location=[lats, lons],
            popup=f"{city}, â‚¬{price}",
            radius=4,
            fill=True,
        )
    )
map.add_child(feature_group)

In [ ]:
fname = 'test_colorbar.html'


base_lat = 50.682294344
base_lon = 10.939628989
f_map = folium.Map(location=[base_lat,base_lon], tiles="OpenStreetMap", zoom_start=17)

lat_ = [50.6823, 50.6822, 50.6821, 50.6820, 50.6819]
lon_ = [10.9396291, 10.9396279, 10.9396269, 10.9396265, 10.9396261]
acc_ = [11.0,44.5,149.9,319.1,540.0,752.6]

colormap = cm.LinearColormap(colors=['darkblue', 'blue', 'cyan', 'yellow', 'orange', 'red'],
                             index=[0, 25, 62.5, 156.25, 390.6, 1000], vmin=0, vmax=1000,
                             caption='Total Standard deviation at the point[mm]')

fg = folium.FeatureGroup(name=fname.split('.')[0])    

for pt in range(len(lat_)):

    color = colormap(acc_[pt])
    fg.add_child(folium.CircleMarker(location=[lat_[pt],lon_[pt]],
                                     radius=6,
                                     fill=True,
                                     color=color,
                                     fill_color=color))

f_map.add_child(fg)
f_map.add_child(colormap)
f_map

In [ ]:
final = pd.read_csv('../../app/costs.csv', index_col=[0])

map = folium.Map(location=[52.2129919, 5.2793703],zoom_start=7, tiles="cartodbdark_matter")
feature_group = folium.FeatureGroup("Locations")

lats = final['latitude'].tolist()
lons = final['longitude'].tolist()
city = final['city'].tolist()
price = final['price'].tolist()
acc_ = final['price'].unique().tolist()

for lats, lons, price, city in zip(lats, lons, price, city):
    color = colormap(acc_.index(price))
    feature_group.add_child(
        folium.CircleMarker(
            location=[lats, lons],
            radius=6,
            fill=True,
            color=color,
            fill_color=color))
map.add_child(feature_group)

In [ ]:
for lat, lon, traffic_q, traffic, bike, city in zip(df['latitude'], df['longitude'], df['traffic_index_quartile'], df['traffic_index'], df['bike_score'], df['city']):
    folium.CircleMarker(
        [lat, lon],
        radius=.15*bike,
        popup = ('City: ' + str(city).capitalize() + '<br>'
                 'Bike score: ' + str(bike) + '<br>'
                 'Traffic level: ' + str(traffic) +'%'
                ),
        color='b',
        key_on = traffic_q,
        threshold_scale=[0,1,2,3],
        fill_color=colordict[traffic_q],
        fill=True,
        fill_opacity=0.7
        ).add_to(traffic_map)
traffic_map

In [ ]:
import seaborn as sns
print(sns.palplot(sns.color_palette("coolwarm", 33)))
print(sns.palplot(sns.color_palette("flare", 33)))
print(sns.palplot(sns.color_palette("viridis", 33)))
print(sns.palplot(sns.color_palette("Spectral", 33)))

In [ ]:
up = sns.palplot(sns.color_palette("Spectral", 33))

In [ ]:
rgb = [(0.15, 0.25, 0.35), (0.35, 0.55, 0.51), (0.5, 0.95, 0.34)]
= sns.palplot(sns.blend_palette(rgb, n_colors=10))

In [ ]:
sns.deep.values

In [ ]:
pal = sns.color_palette("magma")
print(pal)
sns.palplot(pal)

In [ ]:
color_pallete = (sns.color_palette("Spectral", 33))
color_pallete = color_pallete.as_hex()
c = color_pallete[1]
c